package com.itra.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "users")
public class User {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    @NotNull
    private String name;
    @NotNull
    private String nickname;
    @NotNull
    private String email;
    @NotNull
    private String password;
    private String photo;
    @NotNull
    private int role;

    @ManyToMany(mappedBy = "users")
    private List<Project> projects = new ArrayList<>();


    public User() { }

    public User(long id) {
        this.id = id;
    }

    public User(String name, String nickname, String email, String password, int role ) {
        this.email = email;
        this.name = name;
        this.nickname=nickname;
        this.password=password;
        this.role=role;
    }
    public User(String name, String nickname, String email, String password, String photo, int role ) {
        this.email = email;
        this.name = name;
        this.nickname=nickname;
        this.password=password;
        this.photo=photo;
        this.role=role;
    }

    // Getter and setter methods


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public int getRole() {
        return role;
    }

    public void setRole(int role) {
        this.role = role;
    }

    public List<Project> getProjects() {
        return projects;
    }

    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }
}
